[project]
name = "twiga_graph_db"
requires-python = ">=3.12"
version = "0.1.0"
dependencies = [
    "langchain>=0.3.27",
    "langchain-experimental>=0.3.4",
    "langchain-neo4j>=0.5.0",
    "langchain-openai>=0.3.30",
    "neo4j>=5.28.2",
    "numpy>=2.3.2",
]
